num_members: 1

data:
  dataset: tinyimagenet200
  num_classes: 200
  crop: True #!
  test_crop: False #!
  inset: False #!
  test_inset: False #!
  color: False #!
  test_color: False #!
  brightness: False #!
  test_brightness: False #!

data:
  dataset: cifar100
  num_classes: 100
  crop: False #!
  test_crop: False #!
  inset: False #!
  test_inset: False #!
  color: False #!
  test_color: False #!
  brightness: False #!
  test_brightness: False #!
  
training:
  nb_epochs: 300
  batch_size: 64
  dataset_wrapper:
    mixmo:
      mix_method:
        method_name: null
        prob: 1
        replacement_method_name: mixup
      alpha: 2
      weight_root: 3
    msda:
      beta: 1
      prob: 0.5
      mix_method: null
    da_method: null
  batch_sampler:
    batch_repetitions: 1
    proba_input_repetition: 0

model_wrapper:
  name: classifier
  network:
    name: wideresnet
    depth: 28
    widen_factor: 10
  loss:
    listloss:
      - name: soft_cross_entropy
        display_name: ce0
        coeff: 1
        input: logits_0
        target: target_0
      - name: soft_cross_entropy
        display_name: ce1
        coeff: "<num_members"
        input: logits_1
        target: target_1
      - name: soft_cross_entropy
        display_name: ce2
        coeff: "<num_members"
        input: logits_2
        target: target_2
    name: multitask
    display_name: main
    l2_reg: 0.0003
  metrics:
    - accuracy
  metrics_only_test:
    - nll
    - accuracytop5
    - diversity
    - ece
    - auc
    - brier
  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0
      nesterov: True
  warmup_period: 782
  lr_schedule:
    name: multigamma_step
    params:
      dict_milestone_to_gamma:
        101: 0.1
        201: 0.1
        226: 0.1
