num_members: 1

data:
  dataset: tinyimagenet200
  num_classes: 200
  crop: False #!
  test_crop: False #!
  inset: False #!
  test_inset: False #!
  color: False #!
  test_color: False #!
  brightness: False #!
  test_brightness: False #!
  n_views: 2

contrastive:
  mode: pretraining
  
training:
  nb_epochs: 1051 #!
  batch_size: 512 #!
  dataset_wrapper:
    mixmo:
      mix_method:
        method_name: null
        prob: 1
        replacement_method_name: mixup
      alpha: 2
      weight_root: 3
    msda:
      beta: 1
      prob: 0.5
      mix_method: null
    da_method: null
  batch_sampler:
    batch_repetitions: 1
    proba_input_repetition: 0

model_wrapper:
  name: classifier
  network:
    name: resnetcontrastivepretraining
    depth: 18
    widen_factor: 1 #!
  loss:
    listloss:
      - name: contrastive
        display_name: contrastive
        coeff: 1
        input: feature
    name: multitask
    display_name: main
    l2_reg: 0
    #aug_loss_weight: 0.1
    #entropy_weight: 0.1
  metrics:
    - accuracy
  metrics_only_test:
    - nll
    - accuracytop5
    - diversity
    - ece
    - auc
    - brier
  optimizer:
    #name: sgd
    #params:
    #  lr: 0.2 #!
    #  momentum: 0.9
    #  weight_decay: 0.0001
    #  nesterov: True
    name: adam
    params:
       lr: 0.0003
       weight_decay: 0.0001
  #warmup_period: 1000 #! For training from scratch
  warmup_period: 1 #! For continue training with cropping
  lr_schedule:
    name: multigamma_step
    params:
      dict_milestone_to_gamma:
        40: 1 #!
        50: 1 #!
        60: 1 #!
        1000: 0.1 #!

