mode: color

dataset: rawfoot

transform: ['h','s','v']
random_aug: False
global_aug: False

li_flag: True #!
load_li: False #!
train_copies: 1 
test_time_aug: False
test_copies: 10 
lr: 0.00001 #!
warmup_period: 10

crop_layer: [3, -1] #!
crop_layer_bias: [1, 3] #!

entropy_weights: [0.3, 0.3, 0.1, 0.1, 0.1, 0.1] #Be careful, this weight is different from old version
entropy_max_thresholds: [0.6,0.6,1.5,1.5,2.0,2.0]
entropy_min_thresholds: [0.0,0.0,0.0,0.0,0.0,0.0]

    
scheduler_sleep_epoch: 0 #!
ConvFeature: True