mode: crop

dataset: cifar100

transform: ['crop']
random_aug: False
global_aug: False

li_flag: True #!
load_li: False #!
train_copies: 1 
test_time_aug: False
test_copies: 10 
lr: 0.00000 #!#!
warmup_period: 10

crop_layer: [2, -1] #!
crop_layer_bias: [1, 3] #!

entropy_weights: [0.2]
#entropy_weights: [0.2] #For supervised
#entropy_weights: [0.03] #For contrastive? 
    
#Be careful of the order of min and max
entropy_max_thresholds: [3.0] #~
entropy_min_thresholds: [2.5] #~

entropy_increase_period: 40
start_entropy: 0.71

scheduler_sleep_epoch: 0 #!
ConvFeature: True

contrastive_train_aug: False
contrastive_train_copies: 2
contrastive_train_output_max: 2
contrastive_test_aug: False
contrastive_test_copies: 2
contrastive_test_output_max: 2

max_black_ratio: 0.2

crop_only_for_tpu: True
zoom_min: 0.3
zoom_max: 1.1 
zoom_step: 50 
translation_min: -1 
translation_max: 1 
translation_step: 50
input_size: 32